### ISSUE TITLE
pHash and licensing question

### ISSUE THREAD

**Issue by starseeker** [Wassasin/tinyphash#1]
Hi!  I note your code is under MIT license, but in the header you describe it as "re-written to pure C from https://github.com/aetilius/pHash" which is GPLv3...

I just wanted to clarify - is this code a clean rewrite, or a refactoring of the pHash code?

**Comment by Wassasin** [comment]
Hello!

This is a clean, but not a blind, rewrite. Thus I see no licensing issue here.

I made this project a while ago, but if I compare the codebase it seems I first took the underlying maths and made my own implementation for it. If I remember correctly some of the operations were not very memory-friendly, and thus unsuitable anyway. The only code actually inspired by the pHash project is contained in [dct_unchecked](https://github.com/Wassasin/tinyphash/blob/master/tinyphash.c#L134). Arguably more was taken from CImg (The C++ Template Image Processing Toolkit).
